// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using realtime_chat.server.Data;

#nullable disable

namespace realtime_chat.server.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("realtime_chat.server.Models.Entities.ChatRoom", b =>
                {
                    b.Property<int>("ChatRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatRoomId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChatRoomId");

                    b.ToTable("ChatRoom");

                    b.HasData(
                        new
                        {
                            ChatRoomId = 1,
                            Name = "Room 1"
                        },
                        new
                        {
                            ChatRoomId = 2,
                            Name = "Room 2"
                        },
                        new
                        {
                            ChatRoomId = 3,
                            Name = "Room 3"
                        },
                        new
                        {
                            ChatRoomId = 4,
                            Name = "Room 4"
                        },
                        new
                        {
                            ChatRoomId = 5,
                            Name = "Room 5"
                        },
                        new
                        {
                            ChatRoomId = 6,
                            Name = "Room 6"
                        },
                        new
                        {
                            ChatRoomId = 7,
                            Name = "Room 7"
                        },
                        new
                        {
                            ChatRoomId = 8,
                            Name = "Room 8"
                        },
                        new
                        {
                            ChatRoomId = 9,
                            Name = "Room 9"
                        },
                        new
                        {
                            ChatRoomId = 10,
                            Name = "Room 10"
                        });
                });

            modelBuilder.Entity("realtime_chat.server.Models.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Downvotes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ChatRoomId = 1,
                            Content = "Message from user1 in Room 1",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2174),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            ChatRoomId = 1,
                            Content = "Message from user2 in Room 1",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2188),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            ChatRoomId = 1,
                            Content = "Message from user3 in Room 1",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2200),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 4,
                            ChatRoomId = 1,
                            Content = "Message from user4 in Room 1",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2212),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 5,
                            ChatRoomId = 1,
                            Content = "Message from user5 in Room 1",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2221),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 6,
                            ChatRoomId = 2,
                            Content = "Message from user1 in Room 2",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2233),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 7,
                            ChatRoomId = 2,
                            Content = "Message from user2 in Room 2",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2244),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 8,
                            ChatRoomId = 2,
                            Content = "Message from user3 in Room 2",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2254),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 9,
                            ChatRoomId = 2,
                            Content = "Message from user4 in Room 2",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2265),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 10,
                            ChatRoomId = 2,
                            Content = "Message from user5 in Room 2",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2302),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 11,
                            ChatRoomId = 3,
                            Content = "Message from user1 in Room 3",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2313),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 12,
                            ChatRoomId = 3,
                            Content = "Message from user2 in Room 3",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2324),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 13,
                            ChatRoomId = 3,
                            Content = "Message from user3 in Room 3",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2335),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 14,
                            ChatRoomId = 3,
                            Content = "Message from user4 in Room 3",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2345),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 15,
                            ChatRoomId = 3,
                            Content = "Message from user5 in Room 3",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2355),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 16,
                            ChatRoomId = 4,
                            Content = "Message from user1 in Room 4",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2365),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 17,
                            ChatRoomId = 4,
                            Content = "Message from user2 in Room 4",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2376),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 18,
                            ChatRoomId = 4,
                            Content = "Message from user3 in Room 4",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2387),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 19,
                            ChatRoomId = 4,
                            Content = "Message from user4 in Room 4",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2397),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 20,
                            ChatRoomId = 4,
                            Content = "Message from user5 in Room 4",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2408),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 21,
                            ChatRoomId = 5,
                            Content = "Message from user1 in Room 5",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2418),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 22,
                            ChatRoomId = 5,
                            Content = "Message from user2 in Room 5",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2429),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 23,
                            ChatRoomId = 5,
                            Content = "Message from user3 in Room 5",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2440),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 24,
                            ChatRoomId = 5,
                            Content = "Message from user4 in Room 5",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2450),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 25,
                            ChatRoomId = 5,
                            Content = "Message from user5 in Room 5",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2460),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 26,
                            ChatRoomId = 6,
                            Content = "Message from user1 in Room 6",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2471),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 27,
                            ChatRoomId = 6,
                            Content = "Message from user2 in Room 6",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2481),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 28,
                            ChatRoomId = 6,
                            Content = "Message from user3 in Room 6",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2491),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 29,
                            ChatRoomId = 6,
                            Content = "Message from user4 in Room 6",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2501),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 30,
                            ChatRoomId = 6,
                            Content = "Message from user5 in Room 6",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2510),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 31,
                            ChatRoomId = 7,
                            Content = "Message from user1 in Room 7",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2543),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 32,
                            ChatRoomId = 7,
                            Content = "Message from user2 in Room 7",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2555),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 33,
                            ChatRoomId = 7,
                            Content = "Message from user3 in Room 7",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2566),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 34,
                            ChatRoomId = 7,
                            Content = "Message from user4 in Room 7",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2576),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 35,
                            ChatRoomId = 7,
                            Content = "Message from user5 in Room 7",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2587),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 36,
                            ChatRoomId = 8,
                            Content = "Message from user1 in Room 8",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2597),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 37,
                            ChatRoomId = 8,
                            Content = "Message from user2 in Room 8",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2607),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 38,
                            ChatRoomId = 8,
                            Content = "Message from user3 in Room 8",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2618),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 39,
                            ChatRoomId = 8,
                            Content = "Message from user4 in Room 8",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2628),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 40,
                            ChatRoomId = 8,
                            Content = "Message from user5 in Room 8",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2638),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 41,
                            ChatRoomId = 9,
                            Content = "Message from user1 in Room 9",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2648),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 42,
                            ChatRoomId = 9,
                            Content = "Message from user2 in Room 9",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2659),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 43,
                            ChatRoomId = 9,
                            Content = "Message from user3 in Room 9",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2669),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 44,
                            ChatRoomId = 9,
                            Content = "Message from user4 in Room 9",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2679),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 45,
                            ChatRoomId = 9,
                            Content = "Message from user5 in Room 9",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2689),
                            Upvotes = 0,
                            UserId = 5
                        },
                        new
                        {
                            MessageId = 46,
                            ChatRoomId = 10,
                            Content = "Message from user1 in Room 10",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2699),
                            Upvotes = 0,
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 47,
                            ChatRoomId = 10,
                            Content = "Message from user2 in Room 10",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2709),
                            Upvotes = 0,
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 48,
                            ChatRoomId = 10,
                            Content = "Message from user3 in Room 10",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2719),
                            Upvotes = 0,
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 49,
                            ChatRoomId = 10,
                            Content = "Message from user4 in Room 10",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2730),
                            Upvotes = 0,
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 50,
                            ChatRoomId = 10,
                            Content = "Message from user5 in Room 10",
                            Downvotes = 0,
                            Timestamp = new DateTime(2024, 3, 21, 13, 4, 17, 163, DateTimeKind.Utc).AddTicks(2740),
                            Upvotes = 0,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("realtime_chat.server.Models.Entities.UserDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserDetail");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "user1@example.com",
                            Password = "123",
                            UserName = "user1"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "user2@example.com",
                            Password = "123",
                            UserName = "user2"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "user3@example.com",
                            Password = "123",
                            UserName = "user3"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "user4@example.com",
                            Password = "123",
                            UserName = "user4"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "user5@example.com",
                            Password = "123",
                            UserName = "user5"
                        });
                });

            modelBuilder.Entity("realtime_chat.server.Models.Entities.Message", b =>
                {
                    b.HasOne("realtime_chat.server.Models.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Message")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("realtime_chat.server.Models.Entities.UserDetail", "User")
                        .WithMany("Message")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("realtime_chat.server.Models.Entities.ChatRoom", b =>
                {
                    b.Navigation("Message");
                });

            modelBuilder.Entity("realtime_chat.server.Models.Entities.UserDetail", b =>
                {
                    b.Navigation("Message");
                });
#pragma warning restore 612, 618
        }
    }
}
